# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\kauti\Desktop\FAce\FacialRecognitionML\preview.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Preview_View_Form(object):
    def setupUi(self, Preview_View_Form):
        Preview_View_Form.setObjectName("Preview_View_Form")
        Preview_View_Form.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Preview_View_Form)
        self.gridLayout.setObjectName("gridLayout")
        self.Image_preview = QtWidgets.QLabel(Preview_View_Form)
        self.Image_preview.setText("")
        self.Image_preview.setObjectName("Image_preview")
        self.gridLayout.addWidget(self.Image_preview, 0, 0, 1, 1)

        self.retranslateUi(Preview_View_Form)
        QtCore.QMetaObject.connectSlotsByName(Preview_View_Form)

    def retranslateUi(self, Preview_View_Form):
        _translate = QtCore.QCoreApplication.translate
        Preview_View_Form.setWindowTitle(_translate("Preview_View_Form", "Form"))
